"""PDF layout only; report content is supplied by the shared section builder."""
from app.compliance.pdf_fonts import pdf_text as text, font_styles, fetch_font
from threading import RLock

_RENDER_LOCK = RLock()


def _write_pdf(html):
    """Retain logical source text alongside shaped glyphs for copy/accessibility.

    WeasyPrint 69's glyph maps can reorder Indic combining marks. ActualText
    is the PDF replacement-text mechanism; it preserves the original text box
    without changing its visible shaping. Keep this version-pinned adapter
    isolated and serialize rendering while its draw hook is installed.
    """
    import pydyf
    import weasyprint.draw as draw
    from weasyprint.text.fonts import FontConfiguration

    with _RENDER_LOCK:
        original = draw.draw_text

        def with_actual_text(stream, textbox, *args, **kwargs):
            stream.begin_marked_content('Span', pydyf.Dictionary({'ActualText': pydyf.String(textbox.text)}))
            try:
                return original(stream, textbox, *args, **kwargs)
            finally:
                stream.end_marked_content()

        draw.draw_text = with_actual_text
        try:
            return html.write_pdf(font_config=FontConfiguration())
        finally:
            draw.draw_text = original


def render_pdf(report, context, data, status_labels):
    import os
    import sys
    from pathlib import Path
    if sys.platform == 'darwin' and 'DYLD_FALLBACK_LIBRARY_PATH' not in os.environ:
        roots = [p for p in ('/opt/homebrew/lib', '/usr/local/lib') if Path(p, 'libpango-1.0.dylib').is_file()]
        if roots:
            os.environ['DYLD_FALLBACK_LIBRARY_PATH'] = ':'.join(roots)
    from weasyprint import HTML

    styles = font_styles() + '''
    @page { size: A4; margin: 18mm; @bottom-right { content: counter(page) " / " counter(pages); font-size: 8pt; color: #666; } }
    body { font-family: NotoSans, NotoSansDevanagari, NotoSansTelugu; font-size: 9.5pt; line-height: 1.45; color: #202020; }
    h1 { font-size: 18pt; margin: 0 0 3mm; } h2 { font-size: 12pt; margin: 6mm 0 2mm; break-after: avoid; }
    p { margin: 2mm 0; } .subtitle { color: #555; font-size: 11pt; }
    table { width: 100%; border-collapse: collapse; table-layout: fixed; }
    td, th { text-align: left; vertical-align: top; padding: 2mm; overflow-wrap: anywhere; border-bottom: .3pt solid #ccc; }
    th { background: #f3f1ec; font-weight: 700; } tr { break-inside: avoid; } thead { display: table-header-group; }
    .meta th { width: 25%; background: white; } .meta { margin: 4mm 0; }
    .verdict { font-weight: 700; font-size: 12pt; margin-top: 5mm; }
    .not_compliant { color: #a82435; } .needs_review { color: #78551a; }
    .caveat, .footer { color: #555; font-size: 8.5pt; } .warning { color: #78551a; }
    .requirements { break-before: page; } .requirements table { font-size: 8pt; }
    .actions td:last-child { width: 20%; } .footer { margin-top: 5mm; }
    '''
    parts = [f'<!doctype html><html><head><meta charset="utf-8"><title>{text(data["title"])}</title><meta name="author" content="BidSense"><style>{styles}</style></head><body>',
             f'<h1>{text(data["title"])}</h1><p class="subtitle">{text(data["subtitle"])}</p><table class="meta">']
    parts += [f'<tr><th>{text(key)}</th><td>{text(value)}</td></tr>' for key, value in data['meta']]
    parts += ['</table>',f'<p class="verdict {data["verdict_key"]}">{text(data["verdict"])}</p>',
              f'<p><b>{text(data["completion_label"])}</b></p>',f'<p class="caveat">{text(data["completion"].caveat)}</p>']
    parts += [f'<p class="warning">Warning: {text(banner)}</p>' for banner in data['banners']]
    for heading, actions in data['groups']:
        parts.append(f'<h2>{text(heading)}</h2><table class="actions">')
        for action in actions:
            clause = f'clause {action.clause_ref}' if action.clause_ref else '—'
            parts.append(f'<tr><td>{text(action.action)}</td><td>{text(clause)}</td></tr>')
        parts.append('</table>')
    parts.append('<section class="requirements"><h2>Every requirement checked</h2><table><colgroup><col style="width:35%"><col style="width:13%"><col style="width:17%"><col style="width:20%"><col style="width:15%"></colgroup><thead><tr>')
    parts += [f'<th>{label}</th>' for label in ('Requirement','Status','Required','Found','Clause')]
    parts.append('</tr></thead><tbody>')
    for item in data['items']:
        p = item.notification_provenance
        reference = ((p.clause_ref or '—') + (f' p{p.source_page}' if p.source_page else '')) if p else '—'
        values = [item.requirement, status_labels[item.status], item.required_value or '—',item.found_value or '—',reference]
        parts.append('<tr>' + ''.join(f'<td>{text(value)}</td>' for value in values) + '</tr>')
    footer = ('Generated by BidSense' + (f' using {context.extracted_by}' if context.extracted_by else '')
              + '. Format and signing rules are always left to a human reviewer, so no bid is ever reported as fully clear.')
    parts.append(f'</tbody></table></section><p class="footer">{text(footer)}</p></body></html>')
    return _write_pdf(HTML(string=''.join(parts), url_fetcher=fetch_font))
