"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { api } from "@/lib/api";
import { LogoMark } from "@/components/Logo";

export default function LoginPage(){
  const router=useRouter(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [mode,setMode]=useState<"login"|"register">("login"); const [role,setRole]=useState<"vendor"|"reviewer">("vendor"); const [reviewerCode,setReviewerCode]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const result=mode==="login"?await api.login(email,password):await api.register({email,password,role,reviewer_code:role==="reviewer"?reviewerCode:undefined});localStorage.setItem("bidsense_token",result.access_token);localStorage.setItem("bidsense_role",result.user.role);router.push("/");router.refresh()}catch(e){setError(e instanceof Error?e.message:"Authentication failed")}finally{setBusy(false)}}
  return <main className="auth-page"><section className="auth-story"><LogoMark className="h-10 w-10"/><p className="eyebrow">Secure workspace</p><h1>Identity first.<br/>Access second.</h1><p>Sign in establishes who you are. Role permissions separately control which tender records you may use.</p></section><form className="auth-form" onSubmit={submit}><p className="eyebrow">{mode==="login"?"Welcome back":"Create account"}</p><h2>{mode==="login"?"Enter your workspace":"Choose your identity"}</h2><label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Password<input type="password" minLength={10} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{mode==="register"&&<><fieldset><legend>Account type</legend><label><input type="radio" checked={role==="vendor"} onChange={()=>setRole("vendor")}/>Vendor</label><label><input type="radio" checked={role==="reviewer"} onChange={()=>setRole("reviewer")}/>Company reviewer</label></fieldset>{role==="reviewer"&&<label>Reviewer invitation code<input type="password" required value={reviewerCode} onChange={e=>setReviewerCode(e.target.value)}/></label>}</>}{error&&<p role="alert" className="review-error">{error}</p>}<button className="btn btn-primary" disabled={busy}>{busy?"Verifying…":mode==="login"?"Sign in":"Create account"}</button><button type="button" className="auth-switch" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"Create an account":"I already have an account"}</button></form></main>}
