"""phase 0: section 6 schema, users, corrigenda

Revision ID: 02f68841166a
Revises: 
Create Date: 2026-09-01 21:38:04.481658
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '02f68841166a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('organisation', sa.String(length=200), nullable=True),
    sa.Column('role', sa.Enum('vendor', 'reviewer', name='user_role'), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('tender_notifications',
    sa.Column('tender_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('issuing_authority', sa.String(length=300), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('submission_deadline', sa.Date(), nullable=True),
    sa.Column('pre_bid_query_deadline', sa.Date(), nullable=True),
    sa.Column('emd_amount_raw', sa.String(length=120), nullable=True),
    sa.Column('emd_amount_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('contract_value_raw', sa.String(length=120), nullable=True),
    sa.Column('contract_value_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('evaluation_criteria', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('technical_requirements', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('submission_format_rules', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_tender_notifications_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tender_notifications'))
    )
    op.create_index(op.f('ix_tender_notifications_owner_user_id'), 'tender_notifications', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_tender_notifications_sector'), 'tender_notifications', ['sector'], unique=False)
    op.create_index('ix_tender_notifications_tender_id', 'tender_notifications', ['tender_id'], unique=True)
    op.create_table('corrigenda',
    sa.Column('corrigendum_id', sa.String(length=120), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('parent_tender_id', sa.String(length=120), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['tender_notifications.id'], name=op.f('fk_corrigenda_notification_id_tender_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrigenda'))
    )
    op.create_index(op.f('ix_corrigenda_corrigendum_id'), 'corrigenda', ['corrigendum_id'], unique=False)
    op.create_index(op.f('ix_corrigenda_notification_id'), 'corrigenda', ['notification_id'], unique=False)
    op.create_table('eligibility_criteria',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('criterion', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('numeric', 'boolean', 'document', name='criterion_type'), nullable=False),
    sa.Column('threshold_raw', sa.String(length=200), nullable=True),
    sa.Column('threshold_amount_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('threshold_number', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=60), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clause_ref', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.CheckConstraint("type <> 'numeric' OR threshold_amount_inr IS NOT NULL OR threshold_number IS NOT NULL OR threshold_raw IS NOT NULL", name=op.f('ck_eligibility_criteria_numeric_criterion_has_threshold')),
    sa.ForeignKeyConstraint(['notification_id'], ['tender_notifications.id'], name=op.f('fk_eligibility_criteria_notification_id_tender_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eligibility_criteria'))
    )
    op.create_index(op.f('ix_eligibility_criteria_is_mandatory'), 'eligibility_criteria', ['is_mandatory'], unique=False)
    op.create_index(op.f('ix_eligibility_criteria_notification_id'), 'eligibility_criteria', ['notification_id'], unique=False)
    op.create_table('mandatory_documents',
    sa.Column('notification_id', sa.Uuid(), nullable=False),
    sa.Column('doc_name', sa.Text(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clause_ref', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['tender_notifications.id'], name=op.f('fk_mandatory_documents_notification_id_tender_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandatory_documents'))
    )
    op.create_index(op.f('ix_mandatory_documents_notification_id'), 'mandatory_documents', ['notification_id'], unique=False)
    op.create_table('vendor_submissions',
    sa.Column('vendor_id', sa.String(length=120), nullable=False),
    sa.Column('vendor_name', sa.Text(), nullable=False),
    sa.Column('notification_id', sa.Uuid(), nullable=True),
    sa.Column('years_in_business', sa.Float(), nullable=True),
    sa.Column('pricing_summary', sa.Text(), nullable=True),
    sa.Column('quoted_price_raw', sa.String(length=120), nullable=True),
    sa.Column('quoted_price_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('eliminated', 'pending', 'shortlisted', name='vendor_status'), nullable=False),
    sa.Column('elimination_reason', sa.Text(), nullable=True),
    sa.Column('elimination_clause_ref', sa.String(length=120), nullable=True),
    sa.Column('elimination_source_page', sa.Integer(), nullable=True),
    sa.Column('elimination_source_snippet', sa.Text(), nullable=True),
    sa.Column('has_technical_approach', sa.Boolean(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status <> 'eliminated') OR (elimination_reason IS NOT NULL)", name=op.f('ck_vendor_submissions_eliminated_requires_reason')),
    sa.ForeignKeyConstraint(['notification_id'], ['tender_notifications.id'], name=op.f('fk_vendor_submissions_notification_id_tender_notifications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_vendor_submissions_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_submissions')),
    sa.UniqueConstraint('notification_id', 'vendor_id', name='uq_vendor_per_tender')
    )
    op.create_index(op.f('ix_vendor_submissions_is_blacklisted'), 'vendor_submissions', ['is_blacklisted'], unique=False)
    op.create_index(op.f('ix_vendor_submissions_notification_id'), 'vendor_submissions', ['notification_id'], unique=False)
    op.create_index(op.f('ix_vendor_submissions_owner_user_id'), 'vendor_submissions', ['owner_user_id'], unique=False)
    op.create_index('ix_vendor_submissions_status', 'vendor_submissions', ['notification_id', 'status'], unique=False)
    op.create_index(op.f('ix_vendor_submissions_vendor_id'), 'vendor_submissions', ['vendor_id'], unique=False)
    op.create_table('corrigendum_changed_fields',
    sa.Column('corrigendum_id', sa.Uuid(), nullable=False),
    sa.Column('field_path', sa.String(length=200), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clause_ref', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['corrigendum_id'], ['corrigenda.id'], name=op.f('fk_corrigendum_changed_fields_corrigendum_id_corrigenda'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrigendum_changed_fields'))
    )
    op.create_index(op.f('ix_corrigendum_changed_fields_corrigendum_id'), 'corrigendum_changed_fields', ['corrigendum_id'], unique=False)
    op.create_table('vendor_certifications',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('doc_present', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clause_ref', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['vendor_submissions.id'], name=op.f('fk_vendor_certifications_submission_id_vendor_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_certifications'))
    )
    op.create_index(op.f('ix_vendor_certifications_submission_id'), 'vendor_certifications', ['submission_id'], unique=False)
    op.create_table('vendor_documents',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('doc_name', sa.Text(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('matched_requirement_id', sa.Uuid(), nullable=True),
    sa.Column('match_method', sa.String(length=20), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clause_ref', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['matched_requirement_id'], ['mandatory_documents.id'], name=op.f('fk_vendor_documents_matched_requirement_id_mandatory_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['vendor_submissions.id'], name=op.f('fk_vendor_documents_submission_id_vendor_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_documents'))
    )
    op.create_index(op.f('ix_vendor_documents_submission_id'), 'vendor_documents', ['submission_id'], unique=False)
    op.create_table('vendor_past_projects',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('client', sa.Text(), nullable=True),
    sa.Column('value_raw', sa.String(length=120), nullable=True),
    sa.Column('value_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clause_ref', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['vendor_submissions.id'], name=op.f('fk_vendor_past_projects_submission_id_vendor_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_past_projects'))
    )
    op.create_index(op.f('ix_vendor_past_projects_submission_id'), 'vendor_past_projects', ['submission_id'], unique=False)
    op.create_table('vendor_turnover',
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount_raw', sa.String(length=120), nullable=True),
    sa.Column('amount_inr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('clause_ref', sa.String(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_snippet', sa.String(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['vendor_submissions.id'], name=op.f('fk_vendor_turnover_submission_id_vendor_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_turnover')),
    sa.UniqueConstraint('submission_id', 'year', name='uq_turnover_per_year')
    )
    op.create_index('ix_vendor_turnover_amount', 'vendor_turnover', ['amount_inr'], unique=False)
    op.create_index(op.f('ix_vendor_turnover_submission_id'), 'vendor_turnover', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_turnover_submission_id'), table_name='vendor_turnover')
    op.drop_index('ix_vendor_turnover_amount', table_name='vendor_turnover')
    op.drop_table('vendor_turnover')
    op.drop_index(op.f('ix_vendor_past_projects_submission_id'), table_name='vendor_past_projects')
    op.drop_table('vendor_past_projects')
    op.drop_index(op.f('ix_vendor_documents_submission_id'), table_name='vendor_documents')
    op.drop_table('vendor_documents')
    op.drop_index(op.f('ix_vendor_certifications_submission_id'), table_name='vendor_certifications')
    op.drop_table('vendor_certifications')
    op.drop_index(op.f('ix_corrigendum_changed_fields_corrigendum_id'), table_name='corrigendum_changed_fields')
    op.drop_table('corrigendum_changed_fields')
    op.drop_index(op.f('ix_vendor_submissions_vendor_id'), table_name='vendor_submissions')
    op.drop_index('ix_vendor_submissions_status', table_name='vendor_submissions')
    op.drop_index(op.f('ix_vendor_submissions_owner_user_id'), table_name='vendor_submissions')
    op.drop_index(op.f('ix_vendor_submissions_notification_id'), table_name='vendor_submissions')
    op.drop_index(op.f('ix_vendor_submissions_is_blacklisted'), table_name='vendor_submissions')
    op.drop_table('vendor_submissions')
    op.drop_index(op.f('ix_mandatory_documents_notification_id'), table_name='mandatory_documents')
    op.drop_table('mandatory_documents')
    op.drop_index(op.f('ix_eligibility_criteria_notification_id'), table_name='eligibility_criteria')
    op.drop_index(op.f('ix_eligibility_criteria_is_mandatory'), table_name='eligibility_criteria')
    op.drop_table('eligibility_criteria')
    op.drop_index(op.f('ix_corrigenda_notification_id'), table_name='corrigenda')
    op.drop_index(op.f('ix_corrigenda_corrigendum_id'), table_name='corrigenda')
    op.drop_table('corrigenda')
    op.drop_index('ix_tender_notifications_tender_id', table_name='tender_notifications')
    op.drop_index(op.f('ix_tender_notifications_sector'), table_name='tender_notifications')
    op.drop_index(op.f('ix_tender_notifications_owner_user_id'), table_name='tender_notifications')
    op.drop_table('tender_notifications')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
