"""extraction cache

Revision ID: 36e69d6f6558
Revises: a4185bb58fbb
Create Date: 2026-09-02 17:29:58.336827
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '36e69d6f6558'
down_revision = 'a4185bb58fbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_cache',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('doc_kind', sa.String(length=32), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_cache')),
    sa.UniqueConstraint('content_hash', 'doc_kind', 'pipeline_version', name='uq_extraction_cache_key')
    )
    op.create_index('ix_extraction_cache_lookup', 'extraction_cache', ['content_hash', 'doc_kind'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_extraction_cache_lookup', table_name='extraction_cache')
    op.drop_table('extraction_cache')
    # ### end Alembic commands ###
