"""vendor liquid assets and net worth

Revision ID: 4eec089baa27
Revises: 5866dd3ed568
Create Date: 2026-09-02 11:05:20.261712
"""
from alembic import op
import sqlalchemy as sa


revision = '4eec089baa27'
down_revision = '5866dd3ed568'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_submissions', sa.Column('liquid_assets_raw', sa.Text(), nullable=True))
    op.add_column('vendor_submissions', sa.Column('liquid_assets_inr', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('vendor_submissions', sa.Column('net_worth_raw', sa.Text(), nullable=True))
    op.add_column('vendor_submissions', sa.Column('net_worth_inr', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_submissions', 'net_worth_inr')
    op.drop_column('vendor_submissions', 'net_worth_raw')
    op.drop_column('vendor_submissions', 'liquid_assets_inr')
    op.drop_column('vendor_submissions', 'liquid_assets_raw')
    # ### end Alembic commands ###
