"""vendor debarment disclosure

Revision ID: 5866dd3ed568
Revises: 62d5dedfc300
Create Date: 2026-09-02 05:04:26.611035
"""
from alembic import op
import sqlalchemy as sa


revision = '5866dd3ed568'
down_revision = '62d5dedfc300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_submissions', sa.Column('debarment_disclosure', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_submissions', 'debarment_disclosure')
    # ### end Alembic commands ###
