"""corrigendum staleness: last_gap_report_at

Revision ID: 5bfd0986e88f
Revises: 4eec089baa27
Create Date: 2026-09-02 16:00:08.837826
"""
from alembic import op
import sqlalchemy as sa


revision = '5bfd0986e88f'
down_revision = '4eec089baa27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_submissions', sa.Column('last_gap_report_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_submissions', 'last_gap_report_at')
    # ### end Alembic commands ###
