"""ingest jobs

Revision ID: 62d5dedfc300
Revises: 265a7d4c39ca
Create Date: 2026-09-02 01:16:50.753912
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '62d5dedfc300'
down_revision = '265a7d4c39ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_jobs',
    sa.Column('kind', sa.Enum('notification', 'submission', name='job_kind'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partial', 'failed', name='job_status'), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('tender_id', sa.String(length=255), nullable=True),
    sa.Column('vendor_id', sa.String(length=255), nullable=True),
    sa.Column('stage', sa.String(length=120), nullable=True),
    sa.Column('pages_total', sa.Integer(), nullable=True),
    sa.Column('steps_done', sa.Integer(), nullable=False),
    sa.Column('steps_total', sa.Integer(), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_id', sa.Uuid(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_ingest_jobs_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_jobs'))
    )
    op.create_index(op.f('ix_ingest_jobs_status'), 'ingest_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ingest_jobs_tender_id'), 'ingest_jobs', ['tender_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingest_jobs_tender_id'), table_name='ingest_jobs')
    op.drop_index(op.f('ix_ingest_jobs_status'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    # ### end Alembic commands ###
