"""retain source documents for citation click-through

Revision ID: 94fd38faeba5
Revises: 36e69d6f6558
Create Date: 2026-09-02 21:14:25.363757
"""
from alembic import op
import sqlalchemy as sa


revision = '94fd38faeba5'
down_revision = '36e69d6f6558'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tender_notifications', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_tender_notifications_content_hash'), 'tender_notifications', ['content_hash'], unique=False)
    op.add_column('vendor_submissions', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_vendor_submissions_content_hash'), 'vendor_submissions', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_submissions_content_hash'), table_name='vendor_submissions')
    op.drop_column('vendor_submissions', 'content_hash')
    op.drop_index(op.f('ix_tender_notifications_content_hash'), table_name='tender_notifications')
    op.drop_column('tender_notifications', 'content_hash')
    # ### end Alembic commands ###
